//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriPeaks.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TriPeaks.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A card game inspired by the 1991 game for Windows. ähnelt.
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About TriPeaks ähnelt.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cards left = {0} ähnelt.
        /// </summary>
        public static string CardsLeft {
            get {
                return ResourceManager.GetString("CardsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cards left = 0 ähnelt.
        /// </summary>
        public static string CardsLeftDefault {
            get {
                return ResourceManager.GetString("CardsLeftDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are exiting with cards left in play for a penalty of 140 dollars.  - OUCH!! Do you really want to quit? ähnelt.
        /// </summary>
        public static string ExitingPenalty {
            get {
                return ResourceManager.GetString("ExitingPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exiting TiPreaks ähnelt.
        /// </summary>
        public static string ExitingTitle {
            get {
                return ResourceManager.GetString("ExitingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TriPeaks ähnelt.
        /// </summary>
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string GenericCancel {
            get {
                return ResourceManager.GetString("GenericCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string GenericOK {
            get {
                return ResourceManager.GetString("GenericOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TriPeaks Hall of Fame ähnelt.
        /// </summary>
        public static string HallOfFameTitle {
            get {
                return ResourceManager.GetString("HallOfFameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tenth ähnelt.
        /// </summary>
        public static string HOF10th {
            get {
                return ResourceManager.GetString("HOF10th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Champion ähnelt.
        /// </summary>
        public static string HOF1st {
            get {
                return ResourceManager.GetString("HOF1st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Second ähnelt.
        /// </summary>
        public static string HOF2nd {
            get {
                return ResourceManager.GetString("HOF2nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Third ähnelt.
        /// </summary>
        public static string HOF3rd {
            get {
                return ResourceManager.GetString("HOF3rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fourth ähnelt.
        /// </summary>
        public static string HOF4th {
            get {
                return ResourceManager.GetString("HOF4th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fifth ähnelt.
        /// </summary>
        public static string HOF5th {
            get {
                return ResourceManager.GetString("HOF5th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sixth ähnelt.
        /// </summary>
        public static string HOF6th {
            get {
                return ResourceManager.GetString("HOF6th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seventh ähnelt.
        /// </summary>
        public static string HOF7th {
            get {
                return ResourceManager.GetString("HOF7th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eighth ähnelt.
        /// </summary>
        public static string HOF8th {
            get {
                return ResourceManager.GetString("HOF8th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ninth ähnelt.
        /// </summary>
        public static string HOF9th {
            get {
                return ResourceManager.GetString("HOF9th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fame Members ähnelt.
        /// </summary>
        public static string HOFBoxTitle {
            get {
                return ResourceManager.GetString("HOFBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lost - ähnelt.
        /// </summary>
        public static string LostString {
            get {
                return ResourceManager.GetString("LostString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have {0} giving you a ${1} bonus! ähnelt.
        /// </summary>
        public static string PeakConqueredInfo {
            get {
                return ResourceManager.GetString("PeakConqueredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die reached Peak {0} ähnelt.
        /// </summary>
        public static string ReachedPeakN {
            get {
                return ResourceManager.GetString("ReachedPeakN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are trying to deal with cards left in play for a penalty of 140 dollars. Do you really want to redeal? ähnelt.
        /// </summary>
        public static string RedealPenalty {
            get {
                return ResourceManager.GetString("RedealPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TriPeaks Penalty ähnelt.
        /// </summary>
        public static string RedealPenaltyTitle {
            get {
                return ResourceManager.GetString("RedealPenaltyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a Card Back ähnelt.
        /// </summary>
        public static string SelectBackTitle {
            get {
                return ResourceManager.GetString("SelectBackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tri-Conquered ähnelt.
        /// </summary>
        public static string TriConquered {
            get {
                return ResourceManager.GetString("TriConquered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Won $0 ähnelt.
        /// </summary>
        public static string WinLossDefault {
            get {
                return ResourceManager.GetString("WinLossDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Won  ähnelt.
        /// </summary>
        public static string WonString {
            get {
                return ResourceManager.GetString("WonString", resourceCulture);
            }
        }
    }
}
